title: <p align="center"> Mikhala Stepek </p>

logo: "/images/profnew.png?raw=true"

description:
  <p align="center">
  <a href="resume_new.pdf" target="_blank" >Resume</a> |
  <a href="https://www.linkedin.com/in/mikhalastepek/" target="_blank" >LinkedIn</a> |
  <a href="https://github.com/mikhalastepek" target="_blank" >GitHub</a>
  </p>
  
  <p align="justify">
  I'm a recent graduate (Magna cum laude) from the University of Miami, with a BSBA in Business Analytics and Business Technology and a Spanish minor. I am passionate about people, learning, and problem solving, and I approach my work with creativity and curiosity. I also love traveling, yoga, and being in nature:).
  <br><br>
  In summer 2023 I interned for the Executive IT team at Mars Inc, where I completed projects involving increasing digital adoption, automating workflows, and organizing data. I've also interned for a local business in Spain and tutored students for various classes at UM.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
