title: <p align="center"> Mikhala Stepek </p>

logo: "/images/profnew.png?raw=true"

description:
  <p align="center">
  <a href="resume.pdf" target="_blank" >Resume</a> |
  <a href="https://www.linkedin.com/in/mikhalastepek/" target="_blank" >LinkedIn</a> |
  <a href="https://github.com/mikhalastepek" target="_blank" >GitHub</a>
  </p>
  
  <p align="justify">
  I am expecting to graduate in May 2024 from the University of Miami, pursuing a BSBA with a double major in Business Analytics and Business Technology and a minor in Spanish. 
  <br><br>
  Last summer (May-August 2023) I interned for the Executive IT team at Mars Inc, where I was an Executive Technology and Computing Intern. I completed projects involving internal IT education, increasing digital adoption, automating workflows, and organizing data.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
