title: <p align="center"> Mikhala Stepek </p>

logo: "/images/profnew.png?raw=true"

description:
  <p align="center">
  <a href="resume_new.pdf" target="_blank" >Resume</a> |
  <a href="https://www.linkedin.com/in/mikhalastepek/" target="_blank" >LinkedIn</a> |
  <a href="https://github.com/mikhalastepek" target="_blank" >GitHub</a>
  </p>
  
  <p align="justify">
  I'm a 2024 graduate (Magna cum laude) from the University of Miami with a BSBA in Business Analytics and Business Technology and a Spanish minor (3.9 gpa). I am passionate about people, learning, and problem solving, and I pride myself on approaching my work with creativity and a smile. I also love traveling, yoga, and being in nature :).
  <br><br>
  In 2023 I completed 2 internships, one of which was for the Executive IT team at Mars Inc, where I promoted digital adoption by creating educational content about technology, automated workflows by designing a PowerBI dashboard, and organized Excel data and SharePoint content.  The other was a  business development internship for a tourism business in Seville, Spain. I also have experience tutoring and doing outreach for campus orgs.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
